#!/bin/bash
# Colour variables
g="\e[1;32m"
y="\e[0;93m"
r="\e[0m"

# File variables
QF="$XDG_DATA_HOME/yt-boat/yt-boat.queue"

# Functions
OK () {
	echo -e "${g}$1${r}" 1>&2
}

OK_EXIT () {
	echo -e "${g}$1${r}" 1>&2
	exit 0
}

ERR () {
	echo -e "${y}yt-boat: Error: ${1:-"Unknown: Please submit an issue or contact me \
	as this is probably an error with the code itself"}${r}" 1>&2
	exit 1
}


QUEUE () {
	echo -e "There are ${g}$(wc -l $QF | cut -c 1)${r} vidoes in the queue:"
	for i in $(cat $QF)
	do
		echo -e "$(yt-dlp -s --no-warnings --ignore-config --print title $i) - $(($(yt-dlp -s --no-warnings --ignore-config --print duration $i) / 60)):$(($(yt-dlp -s --no-warnings --ignore-config --print duration $i) % 60)) ${g}$i${r}"
	done
}

HELP () {
	echo -e "Usage:\nyt-boat [option]\noptions:\n\
a add [url]                  Adds video the full, provided url to the queue (eg if you want to download from a different frontend)\n\
aa add-alternative [url]     Adds url to the queue\n\
d download                   Downloads videos in the queue\n\
c clear                      Clears the queue\n\
q queue                      Shows the urls in the queue\n\
h help                       Shows this help message\n\
\n\
In newsboat\n\
<macro> a Adds current video's ID to queue\n\
<macro> l Adds the full, provided url to the queue (eg if you want to download from a different frontend)\n\
<macro> d Downloads the urls in the queue\n\
<macro> c Clears the urls in the queue\n\
<macro> q Shows the urls in the queue\n\
<macro> h Shows this help message"
}

# Options
while test "$#" -gt 0; do
	case "$1" in
		a|add|-a|--add)
			shift
				for i in "$@"
				do
					echo "$i" | grep -o -P "(?:v=|\/embed\/|\/1\/|\/v\/)([^&\n?#]+)" | cut -c 3- >> $QF
				done
				OK_EXIT "Videos added to queue"
			;;
		
		aa|add-alternative|-aa|--add-alternative)
			shift
				for i in $@
				do
					echo $i >> $QF
				done
				OK_EXIT "Video added to queue"
			;;


		d|download|-d|--download)
			if yt-dlp -a "$QF"; then
				: > $QF
				OK_EXIT "Videos downloaded"
			else
				ERR "Probably unsupported url or invalid format hardcoded in your yt-dlp config"
			fi
			;;

		c|clear|-c|--clear)
			if : > $QF; then
				OK_EXIT "Queue cleared"
			else
				ERR
			fi
			;;

		q|queue|-q|--queue)
		shift
			if QUEUE; then
				OK_EXIT
			else
				ERR "Queue file may not exist, see FAQ's"
			fi
			;;

		h|help|-h|--help)
			if HELP; then
				OK_EXIT
			else
				ERR
			fi
			;;

        	-hnb)
			clear
			if echo -e "$(HELP)"; then
				OK "Press enter to go back to newsboat"
				read
				OK_EXIT
			else
				ERR
			fi
			;;

		-qnb)
			clear
			if echo -e "$(QUEUE)"; then
				OK "Press enter to go back to newsboat"
				read
				OK_EXIT
			else
				ERR
			fi
			;;

		*)
			shift
			echo -e "${y}Not a valid option${r}"
			HELP
			;;
	esac
	shift
done
