#!/bin/bash
# Colour variables
g="\e[1;32m"
y="\e[0;93m"
r="\e[0m"

# File variables
queue_file="/home/leon/.local/share/yt-boat/newsboat.queue"

# Functions
ERR_ () {
	echo -e "${y}yt-boat: line $LINENO: Error: ${1:-"Unknown: Please submit an issue or contact me \
	as this is probably an error with the code itself"}${r}" 1>&2
	exit 1
}

OK_ () {
	echo -e "${g}${1}${r}" 1>&2
	exit 0
}

QUEUE_ () {
	echo -e "There are ${g}$(wc -l /home/leon/.local/share/yt-boat/newsboat.queue | cut -c 1)${r} vidoes in the queue:"
	cat /home/leon/.local/share/yt-boat/newsboat.queue
}

HELP_ () {
	echo -e "Usage:\nyt-boat [option]\noptions:\n\
-a --add [url]                  Adds video the full, provided url to the queue (eg if you want to download from a different frontend)\n\
-aa --add-alternative [url]     Adds url to the queue\n\
-d --download                   Downloads videos in the queue\n\
-c --clear                      Clears the queue\n\
-q --queue                      Shows the urls in the queue\n\
-u --update                     Updates to the latest version of yt-boat\n\
-h --help                       Shows this help message\n\
\n\
In newsboat\n\
<macro> a Adds current video's ID to queue\n\
<macro> l Adds the full, provided url to the queue (eg if you want to download from a different frontend)\n\
<macro> d Downloads the urls in the queue\n\
<macro> c Clears the urls in the queue\n\
<macro> q Shows the urls in the queue\n\
<macro> u Updates to the latest version of yt-boat\n\
<macro> h Shows this help message"
}

# Options
while true; do
read -p "> " choice
	case "$choice" in
		a|add)
			shift
				read | echo "$1" ; for i in "$@"
				do
					echo "$i" | grep -o -P "(?:v=|\/embed\/|\/1\/|\/v\/)([^&\n?#]+)" | cut -c 3- >> $XDG_DATA_HOME/yt-boat/newsboat.queue
				done
				OK_ "Videos added to queue" || ERR_
			;;
		
		aa|add-alternative)
			shift
				for i in $@
				do
					echo $i >> $XDG_DATA_HOME/yt-boat/newsboat.queue
				done
				OK_ "Video added to queue"
			;;


		d|download)
			if yt-dlp -a "$XDG_DATA_HOME/yt-boat/newsboat.queue"; then
				: > $XDG_DATA_HOME/yt-boat/newsboat.queue
				OK_ "Videos downloaded"
			else
				ERR_ "Probably unsupported url"
			fi
			;;

		c|clear)
			if : > $XDG_DATA_HOME/yt-boat/newsboat.queue; then
				OK_ "Queue cleared"
			else
				ERR_
			fi
			;;

		q|queue)
		shift
			if QUEUE_; then
				OK_
			else
				ERR_ "Queue file may not exist, see FAQ's"
			fi
			;;

		h|help)
			if HELP_; then
				OK_
			else
				ERR_
			fi
			;;

		u|update)
			if wget -o /tmp/log -P $XDG_DATA_HOME/yt-boat https://github.com/flufficat/yt-boat/releases/latest/download/yt-boat.tar.gz; then
				tar -C $XDG_DATA_HOME/yt-boat -xf $XDG_DATA_HOME/yt-boat/yt-boat.tar.gz && \
				chmod +x $XDG_DATA_HOME/yt-boat/yt-boat/yt-boat && \
				sudo mv /usr/local/bin/yt-boat /usr/local/bin/yt-boat_old && \
				sudo mv $XDG_DATA_HOME/yt-boat/yt-boat/yt-boat /usr/local/bin && \
				sudo rm -r $XDG_DATA_HOME/yt-boat/yt-boat && \
				sudo mv  $XDG_DATA_HOME/yt-boat/yt-boat.tar.gz $XDG_DATA_HOME/Trash/files && \
				if sudo mv /usr/local/bin/yt-boat_old $XDG_DATA_HOME/Trash/files; then
					OK_ "Updated Sucessfully"
				else
					ERR_
				fi
			else
				ERR_ "Download failure"
			fi
			;;

        -hnb)
			clear
			if echo -e "$(HELP_)"; then
				echo -e "${g}Press enter to go back to newsboat${r}"
				read
				OK_
			else
				ERR_
			fi
			;;

		-qnb)
			clear
			if echo -e "$(QUEUE_)"; then
				echo -e "${g}Press enter to go back to newsboat${r}"
				read
				OK_
			else
				ERR_
			fi
			;;

		*)
			shift
			echo -e "${y}Not a valid option${r}"
			HELP_
			ERR_
			;;
	esac
	shift
done
