complete -c yt-boat -s a -l add -x   -d "Adds video the provided url to the queue"
complete -c yt-boat -s d -l download -d "Downloads videos in the queue"
complete -c yt-boat -s c -l clear    -d "Clears the queue"
complete -c yt-boat -s q -l queue    -d "Shows the urls in the queue"
complete -c yt-boat -s h -l help     -d "Shows this help message"
