#!/bin/bash
# Colour variables
green="\e[1;32m"
red="\e[1;31m"
yellow="\e[0;93m"
reset="\e[0m"

# File variables
QF="$XDG_DATA_HOME/yt-boat/yt-boat.queue"

# Functions
ERR_ () {
	echo -e "${yellow}yt-boat: Error: ${1:-"Unknown: Please submit an issue or contact me \
	as this is probably an error with the code itself"}${reset}" 1>&2
	exit 1
}

OK_ () {
	echo -e "${green}${1}${reset}" 1>&2
	exit 0
}

QUEUE_ () {
	echo -e "There are ${green}$(wc -l $QF | cut -c 1)${reset} vidoes in the queue:"
	for i in $(cat $QF)
	do
		echo -e "$(yt-dlp -s --no-warnings --ignore-config --print title $i) - $(($(yt-dlp -s --no-warnings --ignore-config --print duration $i) / 60)):$(($(yt-dlp -s --no-warnings --ignore-config --print duration $i) % 60)) ${green}$i${reset}"
	done
}

HELP_ () {
	echo -e "Usage:\nyt-boat [option]\noptions:\n\
a add [url]                  Adds video the full, provided url to the queue (eg if you want to download from a different frontend)\n\
aa add-alternative [url]     Adds url to the queue\n\
d download                   Downloads videos in the queue\n\
c clear                      Clears the queue\n\
q queue                      Shows the urls in the queue\n\
h help                       Shows this help message\n\
\n\
In newsboat\n\
<macro> a Adds current video's ID to queue\n\
<macro> l Adds the full, provided url to the queue (eg if you want to download from a different frontend)\n\
<macro> d Downloads the urls in the queue\n\
<macro> c Clears the urls in the queue\n\
<macro> q Shows the urls in the queue\n\
<macro> h Shows this help message"
}

# Options
while test "$#" -gt 0; do
	case "$1" in
		a|add|--add)
			shift
				for i in "$@"
				do
					echo "$i" | grep -o -P "(?:v=|\/embed\/|\/1\/|\/v\/)([^&\n?#]+)" | cut -c 3- >> $QF
				done
				OK_ "Videos added to queue" || ERR_
			;;
		
		aa|add-alternative|--add-alternative)
			shift
				for i in $@
				do
					echo $i >> $QF
				done
				OK_ "Video added to queue"
			;;


		d|download|--download)
			if yt-dlp -a "$QF"; then
				: > $QF
				OK_ "Videos downloaded"
			else
				ERR_ "Probably unsupported url or invalid format hardcoded in your yt-dlp config"
			fi
			;;

		c|clear|--clear)
			if : > $QF; then
				OK_ "Queue cleared"
			else
				ERR_
			fi
			;;

		q|queue|--queue)
		shift
			if QUEUE_; then
				OK_
			else
				ERR_ "Queue file may not exist, see FAQ's"
			fi
			;;

		h|help|--help)
			if HELP_; then
				OK_
			else
				ERR_
			fi
			;;

        	-hnb)
			clear
			if echo -e "$(HELP_)"; then
				echo -e "${green}Press enter to go back to newsboat${reset}"
				read
				OK_
			else
				ERR_
			fi
			;;

		-qnb)
			clear
			if echo -e "$(QUEUE_)"; then
				echo -e "${green}Press enter to go back to newsboat${reset}"
				read
				OK_
			else
				ERR_
			fi
			;;

		*)
			shift
			echo -e "${yellow}Not a valid option${reset}"
			HELP_
			ERR_
			;;
	esac
	shift
done
